CREATE TABLE IF NOT EXISTS MODULES (NAME VARCHAR(255));
DELETE FROM MODULES;
INSERT INTO MODULES (NAME) VALUES ('Docker');
INSERT INTO MODULES (NAME) VALUES ('Fundamentos da Arquitetura de Software');
INSERT INTO MODULES (NAME) VALUES ('Comunicação');
INSERT INTO MODULES (NAME) VALUES ('RabbitMQ');